<section class="categorie">
    <ul class="tags-list">
        <?php
        
            $cat = array(

                    "acajou (1)",
                    "Agencement de bar (1)",
                    "art déco (1)",
                    "Balance (1)",
                    "Barbier (2)",
                    "Bibliothèque (3)",
                    "Bibliothèque de notaire (1)",
                    "bois (1)",
                    "bois recyclé (1)",
                    "Boucherie ancienne (1)",
                    "Bureau (1)",
                    "Canapé (1)",
                    "Canpé (1)",
                    "Chaise bistrot (3)",
                    "chaise de bistrot (1)",
                    "chapeler (1)",
                    "Chevalet (1)",
                    "coffre-fort (3)",
                    "coiffeur (2)",
                    "comptoir (12)",
                    "Comptoir ancien (4)",
                    "Comptoir de bar (5)",
                    "Comptoir de bar en formica (1)",
                    "comptoir de bistrot (3)",
                    "Comptoir de boucherie (1)",
                    "comptoir de boulanger (3)",
                    "Comptoir de boulangerie (2)",
                    "comptoir de café (3)",
                    "Comptoir de drapier (2)",
                    "Comptoir de magasin (2)",
                    "Comptoir de mercerie (3)",
                    "Comptoir de métier (4)",
                    "Comptoir en marbre (5)",
                    "comptoir galbé (1)",
                    "comptoir vitré (5)",
                    "Comptoir-caisse (1)",
                    "confessionnal (1)",
                    "console (2)",
                    "décoration de jardin (1)",
                    "Double-corps (1)",
                    "Element architectural (1)",
                    "Esaclier industriel (1)",
                    "escabeau métallique (1)",
                    "Escalier colimaçon (1)",
                    "Escalier en fonte (1)",
                    "étagère (1)",
                    "Formica (1)",
                    "frigo en bois (2)",
                    "herboristerie (1)",
                    "Industriel (1)",
                    "Intérieur de bistrot (2)",
                    "Intérieur de pharmacie (4)",
                    "laiton (2)",
                    "lambris (1)",
                    "Lavabo en marbre (1)",
                    "Lion couché (1)",
                    "magasin (1)",
                    "Maroquinier (1)",
                    "mercerie (3)",
                    "métal (1)",
                    "meuble (1)",
                    "Meuble à casiers (1)",
                    "meuble à tiroirs (3)",
                    "meuble à volet (1)",
                    "meuble d'administration (1)",
                    "Meuble d'atelier (2)",
                    "meuble d'école (4)",
                    "Meuble d'église (2)",
                    "Meuble d'épicerie (1)",
                    "Meuble d'herboristerie (1)",
                    "Meuble de barbier (8)",
                    "Meuble de bijoutier (2)",
                    "Meuble de boucher (2)",
                    "Meuble de boucherie (2)",
                    "Meuble de charcuterie (1)",
                    "meuble de chocolatier (1)",
                    "meuble de coiffeur (8)",
                    "Meuble de la Banque de France (1)",
                    "Meuble de magasin (1)",
                    "Meuble de mercerie (4)",
                    "Meuble de métier (10)",
                    "Meuble de musée (1)",
                    "Meuble de notaire (1)",
                    "meuble de parfumerie (1)",
                    "meuble de pâtisserie (1)",
                    "meuble de pharmacie (5)",
                    "Meuble de quincaillerie (2)",
                    "meuble de restaurant (1)",
                    "Meuble en marbre (3)",
                    "Meuble industriel (1)",
                    "miroir (4)",
                    "mobilier (1)",
                    "néogothique (1)",
                    "paire de fauteuils (1)",
                    "patine ancienne (1)",
                    "Pharmacie ancienne (2)",
                    "pieds en fonte (1)",
                    "Pierre bleue (1)",
                    "Pigeonnier (1)",
                    "Placard (1)",
                    "Porte (2)",
                    "porte métallique (1)",
                    "portes coulissantes (2)",
                    "radiateur en fonte (1)",
                    "Radiateur fleuri (1)",
                    "recyclé (1)",
                    "sculpture (1)",
                    "skaï (1)",
                    "statue de jardin (1)",
                    "table (1)",
                    "Table bistrot (1)",
                    "Table d'architecte (1)",
                    "table de bistrot (2)",
                    "Table de boucher (1)",
                    "Table de café (1)",
                    "Table de conférence (1)",
                    "Table de coupe (1)",
                    "Table de couvent (1)",
                    "Table de drapier (2)",
                    "Table de réunion (1)",
                    "Table double-plateaux (1)",
                    "Table en formica (1)",
                    "Table industrielle (3)",
                    "Verrier (1)",
                    "vitres galbées (2)",
                    "Vitrine (5)",
                    "Vitrine de magasin (4)",
                    "Vitrine de musée (2)",
                    "Vitrine de pharmacie (1)",
                    "Vitrine-comptoir (2)",
                    "Zinc (2)"
            );

            foreach ($cat as $value){
                echo "<li> <a href='' >".$value."</a></li>";
            }
        ?>

    </ul>
    <hr />
</section>